### ISSUE TITLE
Project 1 Theory Compiled 2: Graphs

### ISSUE THREAD

**Issue by UniKerogen** [UniKerogen/TempleECE3712#12]
Here is the graph for some of the generation: 
![emagplot](https://user-images.githubusercontent.com/28737574/31737323-19a7bc34-b415-11e7-80a4-e20e1f618703.png)
![fixedx_yz](https://user-images.githubusercontent.com/28737574/31737324-19b80634-b415-11e7-8a1a-65c385dc1032.png)
![fixedy_zx](https://user-images.githubusercontent.com/28737574/31737325-19c53124-b415-11e7-9c69-b37d23c7bd73.png)
![plate](https://user-images.githubusercontent.com/28737574/31737326-19d59852-b415-11e7-86af-2bc1e9b52bf0.png)

**Comment by b-macdonald** [comment]
Could you label the axes? I'm having trouble keeping track of what's going on.

**Comment by UniKerogen** [comment]
Here is a updated version for the graph.
![fixed_yz](https://user-images.githubusercontent.com/28737574/31746797-3029af9a-b437-11e7-90f3-9e67ad6a16e8.png)
![fixedx_yz](https://user-images.githubusercontent.com/28737574/31746798-3056e41a-b437-11e7-80c4-9b243474d357.png)
![fixedy_zx](https://user-images.githubusercontent.com/28737574/31746799-3081f1a0-b437-11e7-8da4-b3bcf029211b.png)

**Comment by UniKerogen** [comment]
![plate](https://user-images.githubusercontent.com/28737574/31746829-5e6dd21e-b437-11e7-88e4-55c86e3ed756.png)

**Comment by UniKerogen** [comment]
Notice: The code has a different coordinate system than the file.

**Comment by b-macdonald** [comment]
Here's some of the plots I did. I have a few more, too.
![bottom](https://user-images.githubusercontent.com/15335397/31803764-913d0150-b523-11e7-83ac-6691db4906da.png)
![top](https://user-images.githubusercontent.com/15335397/31803768-949d721c-b523-11e7-9ce8-5d38fa643b6f.png)
![varyx-alt](https://user-images.githubusercontent.com/15335397/31803774-a03e2b3e-b523-11e7-80e6-77aa94d7767b.png)
![varyz-alt](https://user-images.githubusercontent.com/15335397/31803775-a260cdf4-b523-11e7-840d-8e5f73d100eb.png)
![fields3](https://user-images.githubusercontent.com/15335397/31803788-b256be26-b523-11e7-89ff-493d799dc69d.png)
![fieldsalt2](https://user-images.githubusercontent.com/15335397/31803785-b0ca7c3c-b523-11e7-93d9-ca9e7a5a8256.png)
![fields2](https://user-images.githubusercontent.com/15335397/31803782-abb2fce2-b523-11e7-8145-f1286486db82.png)

**Comment by UniKerogen** [comment]
![screen shot 2017-10-29 at 19 19 46](https://user-images.githubusercontent.com/28737574/32149661-4ad15f32-bcde-11e7-8f78-6e1181ee40dc.png)
![screen shot 2017-10-29 at 19 19 51](https://user-images.githubusercontent.com/28737574/32149662-4adeb1a0-bcde-11e7-90c7-4237d064ef73.png)
