### ISSUE TITLE
Project 1 Theory 2 Compiled: Midpoints

### ISSUE THREAD

**Issue by b-macdonald** [UniKerogen/TempleECE3712#3]
Last week, Dr. Silage told us to evaluate each E field contribution from the midpoint of each DS square. So, the first 'x' value is calculated at 0.05, then 0.15, etc., instead of 0.1 and 0.2 respectively.

**Comment by UniKerogen** [comment]
Hi, there. Thank you for the information. I believe it is regarding Project 1 Compiled Theory 2.

If you take the look at the for loop function, you will notice that the for loop is skipping one point every time, that is how the midpoint kicks in the calculation. You will also notice that the size of Xend and Yend is twice the length of the DS corresponding to the input data.

Feel free to reply if there is any confusion regarding this issue.

**Comment by b-macdonald** [comment]
Hm, I see. 

'DS' should be changed to 0.1, then, I believe. But that does make sense. Interesting way to do it. 

Here's my way:

```
delta = [0.1, 0.01, 0.001];
for change = 1:3
    deltax = (0:(X1/delta(change)))*delta(change) + delta(change)/2;
    deltax = deltax(1:end-1);
    ~ other code ~
end
```

Perhaps still unclear, but it doesn't require skipping values, etc.

**Comment by UniKerogen** [comment]
Your code seems to be varying from those three value for the calculation. If I add this big for loop outside the existing nasty loops, it will dramatically increase the run time. As #1 suggests, once the DS goes smaller, run time will increase and the graph will not pop out as soon as expected. It is a great idea, I will try to implement this once I fix Issue #1

**Comment by b-macdonald** [comment]
Yeah, this isn't meant to exist outside of the existing loops. I use this to calculate all the energies. I'll post my code as a separate file in a second, and you can examine it.

**Comment by UniKerogen** [comment]
I will look into this if I have time before the report. Thank you. I am closing this Issue.
