### ISSUE TITLE
Project 1 Theory 2 Compiled: DS  Value

### ISSUE THREAD

**Issue by b-macdonald** [UniKerogen/TempleECE3712#4]
Unsure why DS = 0.2 at the start. It doesn't seem necessary for any calculations. The surface area of the DS square is 0.1^2, or 0.01 cm^2.

**Comment by UniKerogen** [comment]
Hello, thank you for the information for Project 1 Compiled Theory 2.

I update the description for the Compiled 2. It now states that DS is the length of the differential area. It matters how to generate the grid and calculation for the midpoint.

Feel free to reply is there is any confusion. Please let me know if you there is no further question and I will close this issue.

**Comment by b-macdonald** [comment]
Well, I don't believe that's the length of the differential area. Isn't it 0.1? I could be wrong.

**Comment by UniKerogen** [comment]
If you go all the way done to the line in front of the nasty for loop, there is a new definition for S, which is DS^2, that is being used in the calculation as differential area. The length of the differential area is 0.2. As the grid start at 0, the first start at array[2], which is the midpoint. Then it goes every other point.

**Comment by b-macdonald** [comment]
Isn't the length of the differential area 0.1? It's a 0.1 x 0.1cm square. I don't see how it could be 0.2. Everything else makes sense. 

Your midpoint code makes sense now, thanks.

**Comment by UniKerogen** [comment]
The length is still 0.2. Midpoint will only be used in calculation. Hope it helps.

**Comment by b-macdonald** [comment]
Yeah, I understand the midpoint's role in calculation.

But, could you explain how you determine the length of the differential surface is 0.2 cm? I think the document pretty clearly explains to use 0.1, 0.01, and 0.001. Multiplying by two doesn't make much sense to me.

**Comment by UniKerogen** [comment]
The length is user determined, so you can just change it to 0.1 if you want and 0.01 or 0.001 or else.
