### ISSUE TITLE
Project 1 Theory 2 Compiled: Line 14

### ISSUE THREAD

**Issue by b-macdonald** [UniKerogen/TempleECE3712#6]
Why multiply by zero?

**Comment by UniKerogen** [comment]
Regarding to Project 1 Theory Compiled 2, this line is there in order to generate the graph for the horizontal graph for the first plate.

**Comment by b-macdonald** [comment]
Ah, okay. My graph code is pretty confusing, too, haha!!!

**Comment by UniKerogen** [comment]
Glad helped.
